### ISSUE TITLE
Getting error "Cannot find module"

### ISSUE THREAD

**Issue by rlz** [awerlogus/io-ts-transformer#6]
Trying to use the transformer in my project and constantly getting this error:

```
Error: Cannot find module '.../projects/fabric/src/fab_types'
Require stack:
- .../projects/fabric/node_modules/io-ts-transformer/transformer.js
- .../projects/fabric/node_modules/ttypescript/lib/PluginCreator.js
- .../projects/fabric/node_modules/ttypescript/lib/patchCreateProgram.js
- .../projects/fabric/node_modules/ttypescript/lib/loadTypescript.js
- .../projects/fabric/node_modules/ttypescript/lib/tsc.js
- .../projects/fabric/node_modules/ttypescript/bin/tsc
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.resolve (internal/modules/cjs/helpers.js:79:19)
    at getImportNodeRealPath (.../projects/fabric/node_modules/io-ts-transformer/transformer.js:189:20)
    at .../projects/fabric/node_modules/io-ts-transformer/transformer.js:193:63
    at Array.some (<anonymous>)
    at .../projects/fabric/node_modules/io-ts-transformer/transformer.js:58:38
    at transformSourceFileOrBundle (.../projects/fabric/node_modules/typescript/lib/typescript.js:76501:57)
    at transformation (.../projects/fabric/node_modules/typescript/lib/typescript.js:94068:24)
    at transformRoot (.../projects/fabric/node_modules/typescript/lib/typescript.js:94089:82)
    at Object.map (.../projects/fabric/node_modules/typescript/lib/typescript.js:551:29) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '.../projects/fabric/node_modules/io-ts-transformer/transformer.js',
    '.../projects/fabric/node_modules/ttypescript/lib/PluginCreator.js',
    '.../projects/fabric/node_modules/ttypescript/lib/patchCreateProgram.js',
    '.../projects/fabric/node_modules/ttypescript/lib/loadTypescript.js',
    '.../projects/fabric/node_modules/ttypescript/lib/tsc.js',
    '.../projects/fabric/node_modules/ttypescript/bin/tsc'
  ]
}
```

**Comment by DetachHead** [comment]
seems to be an issue with how the transformer is resolving modules, specifically here
https://github.com/awerlogus/io-ts-transformer/blob/master/transformer.ts#L352

interestingly, it seems to only occur if the module isn't called `main.ts`

i'm no expert as i'm fairly new to the ts compiler API but i'll see if i can figure out how to fix it.
